spring.application.name=GreetingAppProject
spring.datasource.url=jdbc:mysql://localhost:3306/greeting_app
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect